version: 2

updates:
- package-ecosystem: bun
  commit-message:
    prefix: chore
    prefix-development: chore
  cooldown:
    default-days: 7
  directory: /
  labels:
  - automata 🤖
  - chore 🧹
  pull-request-branch-name:
    separator: /
  schedule:
    day: wednesday
    interval: weekly
- package-ecosystem: github-actions
  commit-message:
    prefix: chore
    prefix-development: chore
  cooldown:
    default-days: 7
  directory: /
  labels:
  - automata 🤖
  - chore 🧹
  pull-request-branch-name:
    separator: /
  schedule:
    day: wednesday
    interval: weekly
