name: Request GitHub Actions
description: Request GitHub Actions be added to the pin list.
title: Add GitHub Actions to pin list
labels: [ pins ]
body:
- type: textarea
  id: actions
  attributes:
    description: A list of actions to add, one per line (e.g. actions/setup-ruby).
    label: Actions
    placeholder: |
      owner/action
  validations:
    required: true
