name: Publish Pins

on:
  push:
    branches:
    - main
    paths:
    - pins.json
    - .github/workflows/ci.yaml
  workflow_dispatch: { }

jobs:
  verify:
    name: 1. Verify
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Validate pins.json
      run: |
        set -euo pipefail

        python3 -m json.tool pins.json >/dev/null

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: 2. Deploy
    needs: [ verify ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::488884465262:role/GitHubActionsPins
    - name: Upload pins.json to S3
      run: |
        set -euo pipefail

        aws s3api put-object \
          --body pins.json \
          --bucket unfun.co \
          --key pins.json \
          --cache-control 'public,max-age=300,stale-while-revalidate=60' \
          --content-type application/json
    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id E2E1RKQ7JDHSLZ --paths '/pins.json'
